openapi: 3.1.1

info:
  title: "Abstract File Service"
  summary: "A service for managing files in a storage system."
  version: "0.0.1"

servers:
  - url: "https://localhost:6000/microservice/abstract-file-service/v1"

paths:
  "/files":
    get:
      description: "Returns the id of the files, that include the given tags."
      parameters:
        - $ref: "#/components/parameters/tags" # TODO: What search functions do we want to support?
      responses:
        "200":
          description: "Gets all the fileIds, where the tag is included."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfFileIds"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      description: "Upload a file."
      requestBody:
        required: true
        $ref: "#/components/requestBodies/UploadFileRequest"
      responses:
        "201":
           description: File uploaded successfully
           headers:
             Location:
               description: URL of the uploaded file
               schema:
                 type: string
                 format: uri
           content:
             application/json:
                schema:
                  $ref: "#/components/schemas/FileProperties"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"
        "500":
          $ref: "#/components/responses/InternalServerError"

  "/files/{fileId}":
    get:
      description: "Returns the file."
      parameters:
        - $ref: "#/components/parameters/fileId"
      responses:
        "200":
          $ref: "#/components/responses/FileBody"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"
        "500":
          $ref: "#/components/responses/InternalServerError"

    delete:
      description: "Deletes a file."
      parameters:
        - $ref: "#/components/parameters/fileId"
      responses:
        "200":
          $ref: "#/components/responses/FileId"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  "/properties/{fileId}":
    get:
      description: "Returns Properties of the file."
      parameters:
        - $ref: "#/components/parameters/fileId"
      responses:
        "200":
          description: "Properties of the file"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileProperties"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"
        "500":
          $ref: "#/components/responses/InternalServerError"

    put:
      description: "Updates the properties of a file."
      parameters:
        - $ref: "#/components/parameters/fileId"
      requestBody:
        required: true
        $ref: "#/components/requestBodies/UpdateFileProperties"
      responses:
        "200":
          description: "successfully processed the request."
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  parameters:
    fileId:
      description: "ID to identify the file via a query parameter."
      name: fileId
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/FileId"

    fileLocations:
      description: "Specify in what folders the file should be included. The folders are specified by their fileId."
      name: location
      in: query
      schema:
        type: array
        items:
          $ref: "#/components/schemas/FileId"

    tags:
      description: "Tags given as query."
      name: tag
      in: query
      schema:
        $ref: "#/components/schemas/Tags"

  requestBodies:
    UploadFileRequest:
      description: Upload a file with metadata
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - file
              - name
              - type
              - ownerId
            properties:
              file:
                type: string
                format: binary
                description: The file to upload
              name:
                $ref: "#/components/schemas/Filename"
              ownerId: # TODO: Can we set it ourselves?
                $ref: "#/components/schemas/OwnerId"
              tags:
                $ref: "#/components/schemas/Tags"
              access:
                $ref: "#/components/schemas/AccessRights"

    UpdateFileProperties:
      content:
        application/json:
          schema:
            description: "Update the Metadata of a file."
            type: object
            properties:
                access:
                  $ref: "#/components/schemas/AccessRights"
                metadata:
                   $ref: "#/components/schemas/Metadata"
                tags:
                   $ref: "#/components/schemas/Tags"

  responses:
    ### File Property

    FileProperty:
      description: "Returns properties of a file."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FileProperties"

    FileId:
      description: "Id of a file."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FileId"

    ### File Response

    FileBody:
      description: "Returns the file."
      content:
        text/html: {} # HTML
        image/jpeg: {} # JPG Image
        image/png: {} # PNG Image
        image/gif: {} # GIF Image
        application/msword: {} # Word (.doc)
        application/vnd.openxmlformats-officedocument.wordprocessingml.document:
          {} # Word (.docx)
        application/vnd.ms-excel: {} # Excel (.xls)
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: {} # Excel (.xlsx)
        application/vnd.ms-powerpoint: {} # PowerPoint (.ppt)
        application/vnd.openxmlformats-officedocument.presentationml.presentation:
          {} # PowerPoint (.pptx)
        application/zip: {} # ZIP Archive
        application/pdf: {} # PDF File
        text/calendar: {} # ics File
        application/json:
          schema:
            $ref: "#/components/schemas/DirectoryProperties"

    ### Error Responses

    BadRequest:
      description: "bad request"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

    Unauthorized:
      description: "unauthorized"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

    Forbidden:
      description: "Forbidden"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

    NotFound:
      description: "Not Found"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

    UnsupportedMediaType:
      description: "unsupported media type"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

    InternalServerError:
      description: "internal server error"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"

  schemas:
    ### Successful Response Schemas

    FileProperties:
      description: "Includes all the File Properties."
      type: object
      properties:
        fileId:
         $ref: "#/components/schemas/FileId"

        access:
         $ref: "#/components/schemas/AccessRights"

        metadata:
          $ref: "#/components/schemas/Metadata"

        tags:
          $ref: "#/components/schemas/Tags"

    DirectoryProperties:
      description: "Represents the response if a file is a directory."
      allOf:
        - $ref: "#/components/schemas/FileProperties"
        - $ref: "#/components/schemas/ArrayOfFileProperties"

    ArrayOfFileProperties:
      description: "An array of file properties."
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileProperties"

    ArrayOfFileIds:
      description: "An array of file ids."
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileId"

    ### File Properties
    Metadata:
      description: "Represents additional Metadata for a file"
      allOf:
      - $ref: "#/components/schemas/TimeMetadata"
      - type: object
      required:
        - type
        - name
        - ownerId
      properties:
        type:
          $ref: "#/components/schemas/SupportedMediaType"
        name:
          $ref: "#/components/schemas/Filename"
        ownerId:
          $ref: "#/components/schemas/OwnerId"

    Filename:
      type: string
      description: "The name of the file."

    SupportedMediaType:
      type: string
      description: "MIME type of the file"
      enum:
        - text/html
        - image/jpeg
        - image/png
        - image/gif
        - application/msword
        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
        - application/vnd.ms-excel
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        - application/vnd.ms-powerpoint
        - application/vnd.openxmlformats-officedocument.presentationml.presentation
        - application/zip
        - application/pdf
        - text/calendar
        - application/json

    TimeMetadata:
      type: object
      description: "Includes time related metadata."
      properties:
        createdAt:
          type: string
          format: date-time
          description: "Creation timestamp with seconds precision (ISO 8601)"
        updatedAt:
          type:
            - string
            - "null"
          format: date-time
          description: "Timestamp of the last update with seconds precision (ISO 8601)"

    OwnerId:
      type: integer
      description: "Id to identify the Owner"

    AccessRights:
      type: object
      description: "Specifies which user has access to the file."
      properties:
        read:
          type: array
          items:
            $ref: "#/components/schemas/OwnerId"
        write:
          type: array
          items:
            $ref: "#/components/schemas/OwnerId"
        delete:
          type: array
          items:
            $ref: "#/components/schemas/OwnerId"

    Tags:
      description: "Tags associated with that file"
      type: array
      items:
        type: string

    ### Parameter Schemas
    FileId:
      description: "Used to identify a file."
      type: integer

    ### Error Schemas

    ErrorSchema:
      type: object
      properties:
        title:
          type: string
          description: "A short, human-readable summary of the problem"
        status:
          type: integer
          description: "The HTTP status code applicable to this problem"
        detail:
          type: string
          description: "A explanation specific to this occurrence of the problem"

    SecuritySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT

security:
  - bearerAuth: []
